# Generated by Django 3.1.1 on 2020-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200921_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ksh_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='usd_price',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
