# Generated by Django 3.1.1 on 2020-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200921_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=300, unique=True),
        ),
    ]
