# Generated by Django 3.1.1 on 2020-09-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='speficications',
            new_name='specifications',
        ),
    ]
